{{ range $key, $value := .Values.appServices }}
{{ if $value.enabled }}
---
apiVersion: batch/v1
kind: Job
metadata:
  name: {{ $.Release.Name }}-init-db-{{ $key }}
spec:
  ttlSecondsAfterFinished: 100
  template:
    spec:
      containers:
        - name: createdb
          image: "{{ $.Values.postgresql.image.repository }}:{{ $.Values.postgresql.image.tag }}"
          command: 
            - bash
            - -c
            - "psql -U synapse -h {{ $.Release.Name }}-postgresql -tc \"SELECT 1 FROM pg_database WHERE datname = 'matrix_bridge_{{ $key }}'\" | grep -q 1 || psql -U synapse -h {{ $.Release.Name }}-postgresql -c \"CREATE DATABASE matrix_bridge_{{ $key }}\""
          env:
            - name: PGPASSWORD
              valueFrom:
                secretKeyRef:
                  name: dbcreds
                  key: postgresql-password
      restartPolicy: OnFailure
{{- end }}
{{- end }}